// Generates programs/oilskin/src/generated/ladder.rs from @zyo/shared — the Solana twin of the ABI seam.
// The Anchor program never types a health-factor threshold of its own; it consumes these constants, and
// test/ladder-seam.test.mjs fails the build if the committed file drifts from shared.
//
//   node solana/scripts/gen-ladder.mjs            → writes the file
//   node solana/scripts/gen-ladder.mjs --check    → exit 1 if the committed file differs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  EMERGENCY_HF_MIN_BPS,
  ENTRY_HF_FLOOR,
  HF_HYSTERESIS_MIN_BPS,
  HF_HYSTERESIS_SCALE_BPS,
  HF_HYSTERESIS_SPAN_BPS,
  HF_LADDER,
  LADDER_RUNG_FACTORS_PCT,
  LOAN_DUST_UNITS,
  MIN_LADDER_ENTRY_HF,
  hysteresisFor,
} from "@zyo/shared";

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, "..", "programs", "oilskin", "src", "generated", "ladder.rs");

/** Health factors travel as basis points of 1.0 (1.25 → 12_500) so the program does integer math only. */
const bps = (x) => {
  const v = Math.round(x * 10_000);
  if (Math.abs(v / 10_000 - x) > 1e-9) throw new Error(`not representable in bps: ${x}`);
  return v;
};

const lines = [];
lines.push("// GENERATED by solana/scripts/gen-ladder.mjs from @zyo/shared — DO NOT EDIT.");
lines.push("// Health factors are basis points of 1.0 (12_500 = HF 1.25). Every number here has one source:");
lines.push("// packages/shared/src/health.ts, dust.ts. solana/test/ladder-seam.test.mjs pins this file to them.");
lines.push("#![allow(dead_code)]");
lines.push("");
lines.push(`/// Minimum health factor a freshly opened position must have (shared ENTRY_HF_FLOOR).`);
lines.push(`pub const ENTRY_HF_FLOOR_BPS: u64 = ${bps(ENTRY_HF_FLOOR)};`);
lines.push(`/// A rung disarms once HF climbs back to rung + this: the floor ladder's hysteresis (shared hysteresisFor(ENTRY_HF_FLOOR)).`);
lines.push(`pub const HF_HYSTERESIS_BPS: u64 = ${bps(hysteresisFor(ENTRY_HF_FLOOR))};`);
lines.push(`/// Debt at or below this many loan-token base units is "fully repaid" (shared LOAN_DUST_UNITS).`);
lines.push(`pub const LOAN_DUST_UNITS: u64 = ${LOAN_DUST_UNITS};`);
lines.push("");
lines.push("/// The per-position ladder's derivation (shared `ladderBpsFor`, BUILD-PLAN D7 / SOLANA-ARCHITECTURE §14.2):");
lines.push("/// rung_i = round_to_100bps(1_000_000 + (e − 10_000) × k_i) in hundredths of a bp, emergency ≥ the minimum, each");
lines.push("/// milder rung ≥ the next + 100; hysteresis = round_to_100bps(max(min, scale × (e − 10_000) ÷ span)).");
lines.push(`pub const LADDER_RUNG_FACTORS_PCT: [u64; ${LADDER_RUNG_FACTORS_PCT.length}] = [${LADDER_RUNG_FACTORS_PCT.join(", ")}];`);
lines.push(`pub const EMERGENCY_HF_MIN_BPS: u64 = ${EMERGENCY_HF_MIN_BPS};`);
lines.push(`pub const HF_HYSTERESIS_MIN_BPS: u64 = ${HF_HYSTERESIS_MIN_BPS};`);
lines.push(`pub const HF_HYSTERESIS_SCALE_BPS: u64 = ${HF_HYSTERESIS_SCALE_BPS};`);
lines.push(`pub const HF_HYSTERESIS_SPAN_BPS: u64 = ${HF_HYSTERESIS_SPAN_BPS};`);
lines.push(`/// Below this entry HF four rungs do not fit; a record under it (or 0) runs the floor's ladder (shared MIN_LADDER_ENTRY_HF).`);
lines.push(`pub const MIN_LADDER_ENTRY_HF_BPS: u64 = ${bps(MIN_LADDER_ENTRY_HF)};`);
lines.push("");
lines.push("/// The ladder, mildest → most severe, in the order shared HF_LADDER declares it.");
lines.push("#[derive(Clone, Copy, Debug, PartialEq, Eq)]");
lines.push("pub struct Rung {");
lines.push("    pub id: u8,");
lines.push("    /// Fires when HF < hf_bps.");
lines.push("    pub hf_bps: u64,");
lines.push("    /// Cleared when HF >= disarm_hf_bps (= hf_bps + HF_HYSTERESIS_BPS).");
lines.push("    pub disarm_hf_bps: u64,");
lines.push("    /// 1 = mildest … 4 = most severe.");
lines.push("    pub severity: u8,");
lines.push("}");
lines.push("");
HF_LADDER.forEach((r, i) => {
  lines.push(`/// ${r.label}: ${r.action}.`);
  lines.push(`pub const RUNG_${r.id.toUpperCase()}: Rung = Rung { id: ${i}, hf_bps: ${bps(r.hf)}, disarm_hf_bps: ${bps(r.disarmHf)}, severity: ${r.severity} };`);
});
lines.push("");
lines.push(`pub const LADDER: [Rung; ${HF_LADDER.length}] = [${HF_LADDER.map((r) => `RUNG_${r.id.toUpperCase()}`).join(", ")}];`);
lines.push("");
lines.push("/// Rung ids as the keeper instruction carries them (u8), in ladder order.");
HF_LADDER.forEach((r, i) => lines.push(`pub const RUNG_ID_${r.id.toUpperCase()}: u8 = ${i};`));
lines.push("");
const out = lines.join("\n") + "\n";

if (process.argv.includes("--check")) {
  const current = readFileSync(target, "utf8");
  if (current !== out) {
    console.error(`DRIFT: ${target} does not match @zyo/shared — run: node solana/scripts/gen-ladder.mjs`);
    process.exit(1);
  }
  console.log(`ladder seam OK: ${target} matches @zyo/shared (${HF_LADDER.length} rungs)`);
} else {
  writeFileSync(target, out);
  console.log(`wrote ${target} (${HF_LADDER.length} rungs, entry floor ${ENTRY_HF_FLOOR}, hysteresis ${hysteresisFor(ENTRY_HF_FLOOR)})`);
}
