// GENERATED by scripts/sync-solana-idl.mjs from solana/idl/oilskin.json — do not edit by hand.
// The web's Solana encoders read this and nothing else; test/solana-idl.test.ts fails on drift from the committed IDL.
export const OILSKIN_SOLANA_IDL = {
  "address": "Gw2UE3MixYgA8c7nLZC9UF2z3z5dWfzrFW7ESmi5Scog",
  "sha256": "34ccbfc8609a545c871471910bea43d22e3d72c7514f3220d9648d1287ffb2ae",
  "instructions": {
    "borrow": {
      "discriminator": [
        228,
        253,
        131,
        202,
        207,
        116,
        89,
        18
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": false,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "obligation",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_usdc",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.klend_program",
          "writable": false,
          "signer": false,
          "address": "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
        },
        {
          "name": "kamino.lending_market",
          "writable": false,
          "signer": false,
          "address": "GBJ3bzUiMfwC9ugaF3MM68EXMDyTUb5UryRRAcVjEowd"
        },
        {
          "name": "kamino.lending_market_authority",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.zec_reserve",
          "writable": true,
          "signer": false,
          "address": "6e8XcrdencrXBjXtTqYkRS63nS36petvzkV3gBf2ezbH"
        },
        {
          "name": "kamino.usdc_reserve",
          "writable": true,
          "signer": false,
          "address": "EW9vT7g2VH2aTFfcbaXRUCbF7jEfaLwMiJpckwDZwUZd"
        },
        {
          "name": "kamino.zec_mint",
          "writable": false,
          "signer": false,
          "address": "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS"
        },
        {
          "name": "kamino.usdc_mint",
          "writable": false,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "kamino.zec_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "7muPXroaziH8RTD62Ea4gQ3NuAPZswf8Gj7iuPZ6Ae6Y"
        },
        {
          "name": "kamino.zec_collateral_mint",
          "writable": true,
          "signer": false,
          "address": "FQc32zaNbQnUZmQxd3Fqhg3enqfozyX6K74xcCCHw4NU"
        },
        {
          "name": "kamino.zec_collateral_supply",
          "writable": true,
          "signer": false,
          "address": "8yr67socgzkzXYPMPC8KNCh8eLDPjGvqucLGXmCGdwq4"
        },
        {
          "name": "kamino.usdc_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "C7ipQ9XPEncrVhCLXfHE4aCXPSk1HpPQUr127RwgVG9h"
        },
        {
          "name": "kamino.usdc_fee_vault",
          "writable": true,
          "signer": false,
          "address": "HwgFUiBaEHv2QnrpgVxPmWuUC5nqt7iGSna99ZQL8oTB"
        },
        {
          "name": "kamino.scope_prices",
          "writable": false,
          "signer": false,
          "address": "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH"
        },
        {
          "name": "kamino.farms_program",
          "writable": false,
          "signer": false,
          "address": "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr"
        },
        {
          "name": "kamino.instructions_sysvar",
          "writable": false,
          "signer": false,
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "kamino.token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        [
          "amount_usdc",
          "u64"
        ]
      ]
    },
    "close_position": {
      "discriminator": [
        123,
        134,
        81,
        0,
        49,
        68,
        98,
        98
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": false,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "obligation",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_zec",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_usdc",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.klend_program",
          "writable": false,
          "signer": false,
          "address": "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
        },
        {
          "name": "kamino.lending_market",
          "writable": false,
          "signer": false,
          "address": "GBJ3bzUiMfwC9ugaF3MM68EXMDyTUb5UryRRAcVjEowd"
        },
        {
          "name": "kamino.lending_market_authority",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.zec_reserve",
          "writable": true,
          "signer": false,
          "address": "6e8XcrdencrXBjXtTqYkRS63nS36petvzkV3gBf2ezbH"
        },
        {
          "name": "kamino.usdc_reserve",
          "writable": true,
          "signer": false,
          "address": "EW9vT7g2VH2aTFfcbaXRUCbF7jEfaLwMiJpckwDZwUZd"
        },
        {
          "name": "kamino.zec_mint",
          "writable": false,
          "signer": false,
          "address": "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS"
        },
        {
          "name": "kamino.usdc_mint",
          "writable": false,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "kamino.zec_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "7muPXroaziH8RTD62Ea4gQ3NuAPZswf8Gj7iuPZ6Ae6Y"
        },
        {
          "name": "kamino.zec_collateral_mint",
          "writable": true,
          "signer": false,
          "address": "FQc32zaNbQnUZmQxd3Fqhg3enqfozyX6K74xcCCHw4NU"
        },
        {
          "name": "kamino.zec_collateral_supply",
          "writable": true,
          "signer": false,
          "address": "8yr67socgzkzXYPMPC8KNCh8eLDPjGvqucLGXmCGdwq4"
        },
        {
          "name": "kamino.usdc_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "C7ipQ9XPEncrVhCLXfHE4aCXPSk1HpPQUr127RwgVG9h"
        },
        {
          "name": "kamino.usdc_fee_vault",
          "writable": true,
          "signer": false,
          "address": "HwgFUiBaEHv2QnrpgVxPmWuUC5nqt7iGSna99ZQL8oTB"
        },
        {
          "name": "kamino.scope_prices",
          "writable": false,
          "signer": false,
          "address": "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH"
        },
        {
          "name": "kamino.farms_program",
          "writable": false,
          "signer": false,
          "address": "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr"
        },
        {
          "name": "kamino.instructions_sysvar",
          "writable": false,
          "signer": false,
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "kamino.token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": []
    },
    "deposit": {
      "discriminator": [
        242,
        35,
        198,
        137,
        82,
        225,
        242,
        182
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "obligation",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "user_metadata",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "rent",
          "writable": false,
          "signer": false,
          "address": "SysvarRent111111111111111111111111111111111"
        },
        {
          "name": "system_program",
          "writable": false,
          "signer": false,
          "address": "11111111111111111111111111111111"
        },
        {
          "name": "owner_zec",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_zec",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.klend_program",
          "writable": false,
          "signer": false,
          "address": "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
        },
        {
          "name": "kamino.lending_market",
          "writable": false,
          "signer": false,
          "address": "GBJ3bzUiMfwC9ugaF3MM68EXMDyTUb5UryRRAcVjEowd"
        },
        {
          "name": "kamino.lending_market_authority",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.zec_reserve",
          "writable": true,
          "signer": false,
          "address": "6e8XcrdencrXBjXtTqYkRS63nS36petvzkV3gBf2ezbH"
        },
        {
          "name": "kamino.usdc_reserve",
          "writable": true,
          "signer": false,
          "address": "EW9vT7g2VH2aTFfcbaXRUCbF7jEfaLwMiJpckwDZwUZd"
        },
        {
          "name": "kamino.zec_mint",
          "writable": false,
          "signer": false,
          "address": "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS"
        },
        {
          "name": "kamino.usdc_mint",
          "writable": false,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "kamino.zec_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "7muPXroaziH8RTD62Ea4gQ3NuAPZswf8Gj7iuPZ6Ae6Y"
        },
        {
          "name": "kamino.zec_collateral_mint",
          "writable": true,
          "signer": false,
          "address": "FQc32zaNbQnUZmQxd3Fqhg3enqfozyX6K74xcCCHw4NU"
        },
        {
          "name": "kamino.zec_collateral_supply",
          "writable": true,
          "signer": false,
          "address": "8yr67socgzkzXYPMPC8KNCh8eLDPjGvqucLGXmCGdwq4"
        },
        {
          "name": "kamino.usdc_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "C7ipQ9XPEncrVhCLXfHE4aCXPSk1HpPQUr127RwgVG9h"
        },
        {
          "name": "kamino.usdc_fee_vault",
          "writable": true,
          "signer": false,
          "address": "HwgFUiBaEHv2QnrpgVxPmWuUC5nqt7iGSna99ZQL8oTB"
        },
        {
          "name": "kamino.scope_prices",
          "writable": false,
          "signer": false,
          "address": "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH"
        },
        {
          "name": "kamino.farms_program",
          "writable": false,
          "signer": false,
          "address": "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr"
        },
        {
          "name": "kamino.instructions_sysvar",
          "writable": false,
          "signer": false,
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "kamino.token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        [
          "amount_zec",
          "u64"
        ]
      ]
    },
    "deposit_for_burn": {
      "discriminator": [
        215,
        60,
        61,
        46,
        114,
        55,
        128,
        176
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "obligation",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_usdc",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.klend_program",
          "writable": false,
          "signer": false,
          "address": "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
        },
        {
          "name": "kamino.lending_market",
          "writable": false,
          "signer": false,
          "address": "GBJ3bzUiMfwC9ugaF3MM68EXMDyTUb5UryRRAcVjEowd"
        },
        {
          "name": "kamino.lending_market_authority",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.zec_reserve",
          "writable": true,
          "signer": false,
          "address": "6e8XcrdencrXBjXtTqYkRS63nS36petvzkV3gBf2ezbH"
        },
        {
          "name": "kamino.usdc_reserve",
          "writable": true,
          "signer": false,
          "address": "EW9vT7g2VH2aTFfcbaXRUCbF7jEfaLwMiJpckwDZwUZd"
        },
        {
          "name": "kamino.zec_mint",
          "writable": false,
          "signer": false,
          "address": "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS"
        },
        {
          "name": "kamino.usdc_mint",
          "writable": false,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "kamino.zec_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "7muPXroaziH8RTD62Ea4gQ3NuAPZswf8Gj7iuPZ6Ae6Y"
        },
        {
          "name": "kamino.zec_collateral_mint",
          "writable": true,
          "signer": false,
          "address": "FQc32zaNbQnUZmQxd3Fqhg3enqfozyX6K74xcCCHw4NU"
        },
        {
          "name": "kamino.zec_collateral_supply",
          "writable": true,
          "signer": false,
          "address": "8yr67socgzkzXYPMPC8KNCh8eLDPjGvqucLGXmCGdwq4"
        },
        {
          "name": "kamino.usdc_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "C7ipQ9XPEncrVhCLXfHE4aCXPSk1HpPQUr127RwgVG9h"
        },
        {
          "name": "kamino.usdc_fee_vault",
          "writable": true,
          "signer": false,
          "address": "HwgFUiBaEHv2QnrpgVxPmWuUC5nqt7iGSna99ZQL8oTB"
        },
        {
          "name": "kamino.scope_prices",
          "writable": false,
          "signer": false,
          "address": "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH"
        },
        {
          "name": "kamino.farms_program",
          "writable": false,
          "signer": false,
          "address": "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr"
        },
        {
          "name": "kamino.instructions_sysvar",
          "writable": false,
          "signer": false,
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "kamino.token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "cctp.token_messenger_minter_program",
          "writable": false,
          "signer": false,
          "address": "CCTPV2vPZJS2u2BBsUoscuikbYjnpFmbFsvVuJdgUMQe"
        },
        {
          "name": "cctp.message_transmitter_program",
          "writable": false,
          "signer": false,
          "address": "CCTPV2Sm4AdWt5296sk4P66VBZ7bEhcARwFaaS9YPbeC"
        },
        {
          "name": "cctp.sender_authority_pda",
          "writable": false,
          "signer": false,
          "address": "45hzrGLQ2EGo1Ln7QpXjDwb589GDQ9H2aEXXw6ds6BFE"
        },
        {
          "name": "cctp.denylist_account",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "cctp.message_transmitter",
          "writable": true,
          "signer": false,
          "address": "W1k5ijkaSTo5iA5zChNpfzcy796fLhkBxfmJuR8W8HU"
        },
        {
          "name": "cctp.token_messenger",
          "writable": false,
          "signer": false,
          "address": "AawthJCGRmggpfv9MMWV6Jmo9cue4gL9wUZgRBShg58W"
        },
        {
          "name": "cctp.remote_token_messenger",
          "writable": false,
          "signer": false,
          "address": "BwmDYtQ7jFj8ddaTmKa7fz9hyuK9n58mvc8G7DYNcKjM"
        },
        {
          "name": "cctp.token_minter",
          "writable": false,
          "signer": false,
          "address": "E1bQJ8eMMn3zmeSewW3HQ8zmJr7KR75JonbwAtWx2bux"
        },
        {
          "name": "cctp.local_token",
          "writable": true,
          "signer": false,
          "address": "CRBBbuLCyrkQy4dCTHxqstSmDQv4ajBeUVb9qUdMVaP1"
        },
        {
          "name": "cctp.usdc_mint",
          "writable": true,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "cctp.event_authority",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "message_sent_event_data",
          "writable": true,
          "signer": true,
          "address": null
        },
        {
          "name": "system_program",
          "writable": false,
          "signer": false,
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        [
          "amount",
          "u64"
        ],
        [
          "max_fee",
          "u64"
        ],
        [
          "min_finality_threshold",
          "u32"
        ]
      ]
    },
    "grant": {
      "discriminator": [
        145,
        189,
        68,
        153,
        161,
        231,
        76,
        107
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "grant",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "system_program",
          "writable": false,
          "signer": false,
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        [
          "keeper",
          "pubkey"
        ],
        [
          "params",
          "defined:GrantParams"
        ]
      ]
    },
    "init_account": {
      "discriminator": [
        169,
        188,
        158,
        199,
        9,
        151,
        101,
        125
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "zec_mint",
          "writable": false,
          "signer": false,
          "address": "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS"
        },
        {
          "name": "usdc_mint",
          "writable": false,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "account_zec",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_usdc",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "user_metadata",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "obligation",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "lending_market",
          "writable": false,
          "signer": false,
          "address": "GBJ3bzUiMfwC9ugaF3MM68EXMDyTUb5UryRRAcVjEowd"
        },
        {
          "name": "klend_program",
          "writable": false,
          "signer": false,
          "address": "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
        },
        {
          "name": "rent",
          "writable": false,
          "signer": false,
          "address": "SysvarRent111111111111111111111111111111111"
        },
        {
          "name": "system_program",
          "writable": false,
          "signer": false,
          "address": "11111111111111111111111111111111"
        },
        {
          "name": "token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "associated_token_program",
          "writable": false,
          "signer": false,
          "address": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
        }
      ],
      "args": []
    },
    "keeper_protect": {
      "discriminator": [
        247,
        39,
        31,
        102,
        241,
        154,
        82,
        177
      ],
      "accounts": [
        {
          "name": "keeper",
          "writable": false,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "grant",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "obligation",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_zec",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_usdc",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.klend_program",
          "writable": false,
          "signer": false,
          "address": "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
        },
        {
          "name": "kamino.lending_market",
          "writable": false,
          "signer": false,
          "address": "GBJ3bzUiMfwC9ugaF3MM68EXMDyTUb5UryRRAcVjEowd"
        },
        {
          "name": "kamino.lending_market_authority",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.zec_reserve",
          "writable": true,
          "signer": false,
          "address": "6e8XcrdencrXBjXtTqYkRS63nS36petvzkV3gBf2ezbH"
        },
        {
          "name": "kamino.usdc_reserve",
          "writable": true,
          "signer": false,
          "address": "EW9vT7g2VH2aTFfcbaXRUCbF7jEfaLwMiJpckwDZwUZd"
        },
        {
          "name": "kamino.zec_mint",
          "writable": false,
          "signer": false,
          "address": "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS"
        },
        {
          "name": "kamino.usdc_mint",
          "writable": false,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "kamino.zec_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "7muPXroaziH8RTD62Ea4gQ3NuAPZswf8Gj7iuPZ6Ae6Y"
        },
        {
          "name": "kamino.zec_collateral_mint",
          "writable": true,
          "signer": false,
          "address": "FQc32zaNbQnUZmQxd3Fqhg3enqfozyX6K74xcCCHw4NU"
        },
        {
          "name": "kamino.zec_collateral_supply",
          "writable": true,
          "signer": false,
          "address": "8yr67socgzkzXYPMPC8KNCh8eLDPjGvqucLGXmCGdwq4"
        },
        {
          "name": "kamino.usdc_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "C7ipQ9XPEncrVhCLXfHE4aCXPSk1HpPQUr127RwgVG9h"
        },
        {
          "name": "kamino.usdc_fee_vault",
          "writable": true,
          "signer": false,
          "address": "HwgFUiBaEHv2QnrpgVxPmWuUC5nqt7iGSna99ZQL8oTB"
        },
        {
          "name": "kamino.scope_prices",
          "writable": false,
          "signer": false,
          "address": "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH"
        },
        {
          "name": "kamino.farms_program",
          "writable": false,
          "signer": false,
          "address": "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr"
        },
        {
          "name": "kamino.instructions_sysvar",
          "writable": false,
          "signer": false,
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "kamino.token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        [
          "rung_id",
          "u8"
        ],
        [
          "repay_usdc",
          "u64"
        ],
        [
          "sell_zec",
          "u64"
        ]
      ]
    },
    "repay": {
      "discriminator": [
        234,
        103,
        67,
        82,
        208,
        234,
        219,
        166
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": false,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "obligation",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_usdc",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.klend_program",
          "writable": false,
          "signer": false,
          "address": "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
        },
        {
          "name": "kamino.lending_market",
          "writable": false,
          "signer": false,
          "address": "GBJ3bzUiMfwC9ugaF3MM68EXMDyTUb5UryRRAcVjEowd"
        },
        {
          "name": "kamino.lending_market_authority",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.zec_reserve",
          "writable": true,
          "signer": false,
          "address": "6e8XcrdencrXBjXtTqYkRS63nS36petvzkV3gBf2ezbH"
        },
        {
          "name": "kamino.usdc_reserve",
          "writable": true,
          "signer": false,
          "address": "EW9vT7g2VH2aTFfcbaXRUCbF7jEfaLwMiJpckwDZwUZd"
        },
        {
          "name": "kamino.zec_mint",
          "writable": false,
          "signer": false,
          "address": "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS"
        },
        {
          "name": "kamino.usdc_mint",
          "writable": false,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "kamino.zec_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "7muPXroaziH8RTD62Ea4gQ3NuAPZswf8Gj7iuPZ6Ae6Y"
        },
        {
          "name": "kamino.zec_collateral_mint",
          "writable": true,
          "signer": false,
          "address": "FQc32zaNbQnUZmQxd3Fqhg3enqfozyX6K74xcCCHw4NU"
        },
        {
          "name": "kamino.zec_collateral_supply",
          "writable": true,
          "signer": false,
          "address": "8yr67socgzkzXYPMPC8KNCh8eLDPjGvqucLGXmCGdwq4"
        },
        {
          "name": "kamino.usdc_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "C7ipQ9XPEncrVhCLXfHE4aCXPSk1HpPQUr127RwgVG9h"
        },
        {
          "name": "kamino.usdc_fee_vault",
          "writable": true,
          "signer": false,
          "address": "HwgFUiBaEHv2QnrpgVxPmWuUC5nqt7iGSna99ZQL8oTB"
        },
        {
          "name": "kamino.scope_prices",
          "writable": false,
          "signer": false,
          "address": "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH"
        },
        {
          "name": "kamino.farms_program",
          "writable": false,
          "signer": false,
          "address": "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr"
        },
        {
          "name": "kamino.instructions_sysvar",
          "writable": false,
          "signer": false,
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "kamino.token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        [
          "amount_usdc",
          "u64"
        ]
      ]
    },
    "revoke": {
      "discriminator": [
        170,
        23,
        31,
        34,
        133,
        173,
        93,
        242
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": false,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "grant",
          "writable": true,
          "signer": false,
          "address": null
        }
      ],
      "args": [
        [
          "keeper",
          "pubkey"
        ]
      ]
    },
    "revoke_all": {
      "discriminator": [
        147,
        196,
        234,
        31,
        86,
        199,
        8,
        234
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": false,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        }
      ],
      "args": []
    },
    "set_base_account": {
      "discriminator": [
        142,
        81,
        205,
        64,
        247,
        254,
        130,
        196
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": false,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        }
      ],
      "args": [
        [
          "base_account",
          "{\"array\":[\"u8\",32]}"
        ]
      ]
    },
    "transfer_out": {
      "discriminator": [
        202,
        137,
        44,
        229,
        158,
        255,
        205,
        174
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": true,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "mint",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "account_token",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "owner_token",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "associated_token_program",
          "writable": false,
          "signer": false,
          "address": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
        },
        {
          "name": "system_program",
          "writable": false,
          "signer": false,
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        [
          "amount",
          "u64"
        ]
      ]
    },
    "withdraw": {
      "discriminator": [
        183,
        18,
        70,
        156,
        148,
        109,
        161,
        34
      ],
      "accounts": [
        {
          "name": "owner",
          "writable": false,
          "signer": true,
          "address": null
        },
        {
          "name": "account",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "obligation",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "account_zec",
          "writable": true,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.klend_program",
          "writable": false,
          "signer": false,
          "address": "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"
        },
        {
          "name": "kamino.lending_market",
          "writable": false,
          "signer": false,
          "address": "GBJ3bzUiMfwC9ugaF3MM68EXMDyTUb5UryRRAcVjEowd"
        },
        {
          "name": "kamino.lending_market_authority",
          "writable": false,
          "signer": false,
          "address": null
        },
        {
          "name": "kamino.zec_reserve",
          "writable": true,
          "signer": false,
          "address": "6e8XcrdencrXBjXtTqYkRS63nS36petvzkV3gBf2ezbH"
        },
        {
          "name": "kamino.usdc_reserve",
          "writable": true,
          "signer": false,
          "address": "EW9vT7g2VH2aTFfcbaXRUCbF7jEfaLwMiJpckwDZwUZd"
        },
        {
          "name": "kamino.zec_mint",
          "writable": false,
          "signer": false,
          "address": "A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS"
        },
        {
          "name": "kamino.usdc_mint",
          "writable": false,
          "signer": false,
          "address": "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
        },
        {
          "name": "kamino.zec_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "7muPXroaziH8RTD62Ea4gQ3NuAPZswf8Gj7iuPZ6Ae6Y"
        },
        {
          "name": "kamino.zec_collateral_mint",
          "writable": true,
          "signer": false,
          "address": "FQc32zaNbQnUZmQxd3Fqhg3enqfozyX6K74xcCCHw4NU"
        },
        {
          "name": "kamino.zec_collateral_supply",
          "writable": true,
          "signer": false,
          "address": "8yr67socgzkzXYPMPC8KNCh8eLDPjGvqucLGXmCGdwq4"
        },
        {
          "name": "kamino.usdc_liquidity_supply",
          "writable": true,
          "signer": false,
          "address": "C7ipQ9XPEncrVhCLXfHE4aCXPSk1HpPQUr127RwgVG9h"
        },
        {
          "name": "kamino.usdc_fee_vault",
          "writable": true,
          "signer": false,
          "address": "HwgFUiBaEHv2QnrpgVxPmWuUC5nqt7iGSna99ZQL8oTB"
        },
        {
          "name": "kamino.scope_prices",
          "writable": false,
          "signer": false,
          "address": "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH"
        },
        {
          "name": "kamino.farms_program",
          "writable": false,
          "signer": false,
          "address": "FarmsPZpWu9i7Kky8tPN37rs2TpmMrAZrC7S7vJa91Hr"
        },
        {
          "name": "kamino.instructions_sysvar",
          "writable": false,
          "signer": false,
          "address": "Sysvar1nstructions1111111111111111111111111"
        },
        {
          "name": "kamino.token_program",
          "writable": false,
          "signer": false,
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        [
          "collateral_amount",
          "u64"
        ]
      ]
    }
  },
  "accounts": {
    "Grant": [
      161,
      166,
      11,
      205,
      204,
      135,
      205,
      54
    ],
    "UserAccount": [
      211,
      33,
      136,
      16,
      186,
      110,
      242,
      127
    ]
  },
  "types": {
    "Grant": [
      [
        "account",
        "pubkey"
      ],
      [
        "keeper",
        "pubkey"
      ],
      [
        "bump",
        "u8"
      ],
      [
        "version",
        "u8"
      ],
      [
        "epoch",
        "u64"
      ],
      [
        "expiry_ts",
        "i64"
      ],
      [
        "period_secs",
        "u64"
      ],
      [
        "period_start_ts",
        "i64"
      ],
      [
        "repay_usdc_per_period",
        "u64"
      ],
      [
        "repay_usdc_spent",
        "u64"
      ],
      [
        "sell_zec_per_period",
        "u64"
      ],
      [
        "sell_zec_spent",
        "u64"
      ],
      [
        "max_sell_slippage_bps",
        "u16"
      ],
      [
        "allowed_rungs",
        "u8"
      ],
      [
        "_reserved",
        "{\"array\":[\"u8\",32]}"
      ]
    ],
    "GrantParams": [
      [
        "expiry_ts",
        "i64"
      ],
      [
        "period_secs",
        "u64"
      ],
      [
        "repay_usdc_per_period",
        "u64"
      ],
      [
        "sell_zec_per_period",
        "u64"
      ],
      [
        "max_sell_slippage_bps",
        "u16"
      ],
      [
        "allowed_rungs",
        "u8"
      ]
    ],
    "UserAccount": [
      [
        "owner",
        "pubkey"
      ],
      [
        "bump",
        "u8"
      ],
      [
        "version",
        "u8"
      ],
      [
        "grant_epoch",
        "u64"
      ],
      [
        "obligation",
        "pubkey"
      ],
      [
        "created_slot",
        "u64"
      ],
      [
        "entry_hf_bps",
        "u64"
      ],
      [
        "base_account",
        "{\"array\":[\"u8\",32]}"
      ],
      [
        "_reserved",
        "{\"array\":[\"u8\",24]}"
      ]
    ]
  },
  "errors": [
    {
      "code": 6000,
      "name": "NotOwner",
      "msg": "Only the account owner may do this"
    },
    {
      "code": 6001,
      "name": "OwnerIsPda",
      "msg": "The wallet is a program-derived address; an account owner must be a signing key"
    },
    {
      "code": 6002,
      "name": "EntryHfTooLow",
      "msg": "Health factor after this action is below the entry floor"
    },
    {
      "code": 6003,
      "name": "LtvAboveOffer",
      "msg": "Loan-to-value after this borrow is above what Oilskin offers for this collateral"
    },
    {
      "code": 6004,
      "name": "ExitHfTooLow",
      "msg": "Health factor after this withdraw is below the exit floor and the debt is not dust"
    },
    {
      "code": 6005,
      "name": "ObligationStale",
      "msg": "The obligation was not refreshed in this slot"
    },
    {
      "code": 6006,
      "name": "PriceNotChecked",
      "msg": "The reserve's price was not fully checked at its last refresh"
    },
    {
      "code": 6007,
      "name": "HealthOverflow",
      "msg": "Health arithmetic overflowed"
    },
    {
      "code": 6008,
      "name": "UnexpectedKaminoLayout",
      "msg": "Kamino account layout is not the one this program was built against"
    },
    {
      "code": 6009,
      "name": "WrongKaminoAccount",
      "msg": "A Kamino account is not the one this market uses"
    },
    {
      "code": 6010,
      "name": "ZeroAmount",
      "msg": "Amount must be greater than zero"
    },
    {
      "code": 6011,
      "name": "InvalidGrant",
      "msg": "Grant parameters are invalid"
    },
    {
      "code": 6012,
      "name": "GrantNotLive",
      "msg": "The grant is not live (expired, revoked, or from an older epoch)"
    },
    {
      "code": 6013,
      "name": "RungNotAllowed",
      "msg": "This rung is not allowed by the grant"
    },
    {
      "code": 6014,
      "name": "RungIsNotifyOnly",
      "msg": "The warn rung is notify-only: there is no on-chain action for it"
    },
    {
      "code": 6015,
      "name": "UnknownRung",
      "msg": "Unknown rung id"
    },
    {
      "code": 6016,
      "name": "RungNotCrossed",
      "msg": "The named rung is not crossed: the account is healthier than that"
    },
    {
      "code": 6017,
      "name": "RungUnderstated",
      "msg": "A more severe rung is crossed than the one named"
    },
    {
      "code": 6018,
      "name": "RepayBudgetExceeded",
      "msg": "Repay budget for this period is exhausted"
    },
    {
      "code": 6019,
      "name": "SellBudgetExceeded",
      "msg": "Sell budget for this period is exhausted or selling is not permitted by the grant"
    },
    {
      "code": 6020,
      "name": "ProtectionIneffective",
      "msg": "The action did not lift the health factor to the rung's disarm level and no budget was exhausted"
    },
    {
      "code": 6021,
      "name": "SaleBelowFloor",
      "msg": "Sale proceeds are below the Scope-priced floor"
    },
    {
      "code": 6022,
      "name": "NotRevocable",
      "msg": "Nothing to revoke: no grant exists for this keeper"
    },
    {
      "code": 6023,
      "name": "GrantStillLive",
      "msg": "A live grant exists; revoke it before releasing the obligation"
    },
    {
      "code": 6024,
      "name": "InsufficientUsdcToClose",
      "msg": "The account's USDC balance cannot cover the debt"
    },
    {
      "code": 6025,
      "name": "WrongTokenAccount",
      "msg": "Token account is not the account's associated token account for that mint"
    },
    {
      "code": 6026,
      "name": "NoBaseAccount",
      "msg": "No Base account is recorded for this account; set_base_account first"
    },
    {
      "code": 6027,
      "name": "InvalidBaseAccount",
      "msg": "A Base account must not be zero"
    },
    {
      "code": 6028,
      "name": "ReserveShort",
      "msg": "The burn would leave the Account's USDC under the reserve the debt requires"
    },
    {
      "code": 6029,
      "name": "WrongCctpAccount",
      "msg": "A CCTP account is not the one this program was built against"
    }
  ]
} as const;
