#!/usr/bin/env node
/**
 * sync-abi — regenerate lib/abi/oilskin.generated.ts from the compiled
 * artifact bundle contracts/abi/oilskin-abi.json (itself generated from
 * contracts/out by the contracts engineer's verify-abi.mjs --write).
 *
 * The web encodes ONLY from the generated file; test/abi.test.ts re-reads the
 * artifact and fails on any drift (AUDIT-FINDINGS Part 4: the ABI seam broke
 * twice when areas encoded from a written document).
 *
 *   node scripts/sync-abi.mjs
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const src = resolve(here, "../../contracts/abi/oilskin-abi.json");
const raw = readFileSync(src, "utf8");
const bundle = JSON.parse(raw);
const hash = createHash("sha256").update(raw).digest("hex");

/** Contract → functions/events/errors the web needs. Everything else is left out on purpose. */
const WANT = {
  OilskinAccountFactory: { functions: ["accountOf", "isDeployed", "createAccount", "createAccountAndExec"], events: ["AccountCreated"], errors: true },
  OilskinAccount: { functions: ["owner", "exec", "execWithCallback", "execBatch", "grant", "revoke", "revokeAll", "grantOf", "grantEpoch", "grantTokens", "tokenBudgetOf", "MAX_PERIPHERAL_DEPTH", "PERMIT2", "FACTORY"], events: ["Executed", "Granted", "Revoked", "KeeperSpend"], errors: true },
  StrategyRouter: { functions: ["openLeveragedLp", "openBorrowOnly", "unwind", "sweep", "REGISTRY", "LP_VENUE", "LP_VENUE_DIRECT", "SWAP", "SWAP_DIRECT", "PERMIT2", "USDC"], events: ["LeveragedLpOpened", "BorrowOnlyOpened", "LeveragedLpUnwound", "VenueRepaid", "VenueWithdrawn", "Swept"], errors: true },
  SnuggleLpVenue: { functions: ["positionsOf", "claim", "close", "closeMany", "increase", "poolTokens", "poolOf", "ownedPool", "poolSqrtPriceX96", "performanceBps", "MIN_WIDTH_BPS", "MAX_WIDTH_BPS", "MAX_BAND_BPS", "MAX_REBALANCE_DELAY", "REWARD_TOKEN", "treasury", "ENGINE"], events: ["LpOpened", "LpClosed", "PerformanceFee"], errors: true },
  // The direct Slipstream venue over the cbZEC/USDC pool (2026-09-11): the same ILpVenue surface the
  // dashboard drives, plus the static range it shows and the pool/gauge it binds to.
  SlipstreamLpVenue: { functions: ["positionsOf", "claim", "close", "closeMany", "increase", "poolTokens", "poolOf", "ownedPool", "poolSqrtPriceX96", "positionRange", "unstakedOverflow", "performanceBps", "MIN_WIDTH_BPS", "MAX_WIDTH_BPS", "MAX_BAND_BPS", "REWARD_TOKEN", "treasury", "POOL", "POOL_ID", "NPM", "GAUGE", "SWAP", "TOKEN0", "TOKEN1", "TICK_SPACING"], events: ["LpOpened", "LpMinted", "LpClosed", "PerformanceFee", "StakeSkipped", "SwappedToRatio", "RefundLeft"], errors: true },
  SlipstreamPoolSwapAdapter: { functions: ["minOutFor", "MAX_SLIPPAGE_BPS", "BPS", "POOL", "TOKEN0", "TOKEN1", "TICK_SPACING"], events: ["Swapped"], errors: true },
  ISnuggleVault: { functions: ["positions", "userPositions", "approvedPools"], events: [], errors: false },
  AaveV3Venue: { functions: ["supply", "borrow", "repay", "withdraw", "healthFactor", "liquidationThresholdBps", "maxLtvBps", "debt", "collateral", "borrowRateRay", "enabled", "assetPrice", "PROVIDER"], events: [], errors: true },
  // The venue-aware account read (lib/reads.ts readVenueHealth) talks to WHATEVER venue the registry
  // names through this interface — the Aave venue, the Morpho venue, a future one (audit wave 2, M-HIGH-2).
  ICollateralVenue: { functions: ["healthFactor", "liquidationThresholdBps", "maxLtvBps", "debt", "collateral", "borrowRateRay", "enabled"], events: [], errors: false },
  CollateralRegistry: { functions: ["maxOfferedLtvBps", "entryHfForLtv", "entryHfFloorWad", "config", "isEnabled", "venueOf", "previousVenues", "assets", "pendingVenue", "TIMELOCK_DELAY"], events: ["VenueChangeProposed", "VenueChangeAccepted", "VenueChangeCancelled"], errors: true },
  AerodromeSwapAdapter: { functions: ["minOutFor", "MAX_SLIPPAGE_BPS", "BPS", "ROUTER"], events: ["Swapped"], errors: true },
  IPermit2: { functions: ["permitTransferFrom", "DOMAIN_SEPARATOR"], events: [], errors: false },
  IAerodromeCLPool: { functions: ["slot0", "tickSpacing", "token0", "token1", "fee"], events: [], errors: false },
};

const out = [];
out.push("/* eslint-disable */");
out.push("/**");
out.push(" * GENERATED by scripts/sync-abi.mjs from contracts/abi/oilskin-abi.json — DO NOT EDIT.");
out.push(` * Source: ${bundle.generatedFrom}`);
out.push(` * Bundle sha256: ${hash}`);
out.push(" * test/abi.test.ts fails on any drift between this file and the artifact.");
out.push(" */");
out.push(`export const ABI_BUNDLE_SHA256 = "${hash}" as const;`);
const selectors = {};
for (const [name, want] of Object.entries(WANT)) {
  const c = bundle.contracts[name];
  if (!c) throw new Error(`bundle lacks ${name}`);
  const items = c.abi.filter((it) => {
    if (it.type === "function") return want.functions.includes(it.name);
    if (it.type === "event") return want.events.includes(it.name);
    if (it.type === "error") return want.errors;
    return false;
  });
  for (const fn of want.functions) if (!items.some((it) => it.type === "function" && it.name === fn)) throw new Error(`${name}.${fn} not in bundle`);
  const constName = `${name.replace(/^I/, (m, i) => (name.startsWith("I") && name[1] === name[1].toUpperCase() ? "" : m)).replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase()}_ABI`;
  out.push(`export const ${constName} = ${JSON.stringify(items, null, 2)} as const;`);
  const sels = {};
  for (const [sigText, meta] of Object.entries(c.functions ?? {})) {
    const fnName = sigText.slice(0, sigText.indexOf("("));
    if (want.functions.includes(fnName)) sels[sigText] = meta.selector;
  }
  selectors[name] = sels;
}
out.push(`/** Function selectors as printed by the artifact bundle, for the drift test and for labelling calldata. */`);
out.push(`export const SELECTORS = ${JSON.stringify(selectors, null, 2)} as const;`);
const dest = join(here, "../lib/abi/oilskin.generated.ts");
writeFileSync(dest, out.join("\n") + "\n");
console.log(`wrote ${dest} (bundle ${hash.slice(0, 12)}…)`);
