#!/usr/bin/env node
/**
 * reserve-sizing — the Solana-side USDC reserve against ZEC's real price history.
 *
 *   node services/yield/scripts/reserve-sizing.mjs                 read the dated sample, print the report
 *   node services/yield/scripts/reserve-sizing.mjs --fetch         re-read Kraken and write a new dated sample
 *   node services/yield/scripts/reserve-sizing.mjs --paths 20000   more Monte-Carlo paths (default 10,000)
 *
 * Needs `npm run build -w @zyo/yield` first (imports ../dist). The report is markdown on stdout; the doc
 * `docs/MODEL-RESERVE-2026-09-19.md` carries the copy it was generated from and says so.
 *
 * Source: Kraken's public OHLC endpoint (no key), ZEC/USD, four intervals — 15 min (7.5 days), 1 h (30 days),
 * 4 h (120 days) and 1 day (2 years); each call returns the last 720 candles plus the open one, which is dropped.
 * Rule 3: the sample is dated and committed so the run is reproducible without the network.
 */
import { existsSync, readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ENTRY_HF_FLOOR } from "@zyo/shared";
import {
  demean, frequencyOfDrop, ladderGeometry, logReturns, parseKrakenOhlc, realizedVol, simulateLadder, worstDropWithin,
} from "../dist/src/reserveSizing.js";

const here = dirname(fileURLToPath(import.meta.url));
const samplesDir = resolve(here, "..", "samples");
const argv = process.argv.slice(2);
const flag = (k, d) => { const i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : d; };
const PATHS = Number(flag("--paths", 10_000));

/* ── inputs, every one stated ─────────────────────────────────────────────────────────── */
const ENTRY_HF = 1.625;        // Kamino's 40 % LTV cap against its 65 % LT: 0.65 / 0.40 (VERIFIED-SOLANA-FACTS.md, ZEC reserve rows)
const LT = 0.65;               // liquidationThresholdPct 65 (same table)
const KAMINO_USDC_BORROW_APR = 3.378; // % per year, the curve at the read utilisation (VERIFIED-SOLANA-FACTS.md line "Borrow APR from the curve")
const INTERVALS = [15, 60, 240, 1440];

async function fetchKraken() {
  const series = {};
  for (const iv of INTERVALS) {
    const url = `https://api.kraken.com/0/public/OHLC?pair=ZECUSD&interval=${iv}`;
    const r = await fetch(url, { signal: AbortSignal.timeout(20_000) });
    if (!r.ok) throw new Error(`${url}: HTTP ${r.status}`);
    const j = await r.json();
    if (j.error?.length) throw new Error(`${url}: ${j.error.join("; ")}`);
    const key = Object.keys(j.result).find((k) => k !== "last");
    series[iv] = { pair: key, rows: j.result[key].map((row) => row.slice(0, 5).map(String)) };
  }
  return series;
}

function latestSample() {
  const files = readdirSync(samplesDir).filter((f) => /^zec-usd-kraken-\d{4}-\d{2}-\d{2}\.json$/.test(f)).sort();
  return files.length ? join(samplesDir, files[files.length - 1]) : null;
}

let samplePath = flag("--sample", null);
if (argv.includes("--fetch")) {
  const fetchedAt = new Date().toISOString();
  const series = await fetchKraken();
  samplePath = join(samplesDir, `zec-usd-kraken-${fetchedAt.slice(0, 10)}.json`);
  writeFileSync(samplePath, JSON.stringify({
    source: "Kraken public OHLC, https://api.kraken.com/0/public/OHLC?pair=ZECUSD&interval=<min>; rows are [time, open, high, low, close] as the API returned them (strings), the open candle included and dropped on read",
    fetchedAt, intervalsMin: INTERVALS, series,
  }, null, 1));
  console.error(`reserve-sizing: wrote ${samplePath}`);
}
samplePath ??= latestSample();
if (!samplePath || !existsSync(samplePath)) { console.error("reserve-sizing: no sample — run with --fetch"); process.exit(2); }
const sample = JSON.parse(readFileSync(samplePath, "utf8"));
const S = {};
for (const iv of INTERVALS) S[iv] = { intervalMin: iv, candles: parseKrakenOhlc(sample.series[iv].rows) };

/* ── the report ────────────────────────────────────────────────────────────────────────── */
const pct = (x, d = 2) => `${(x * 100).toFixed(d)} %`;
const pctN = (x, d = 2) => `${x.toFixed(d)} %`;
const iso = (t) => new Date(t * 1000).toISOString().replace(/\.\d+Z$/, "Z");
const L = [];
const geo = ladderGeometry(ENTRY_HF);
const rungBy = (id) => geo.rungs.find((r) => r.id === id);

L.push(`_Generated by \`node services/yield/scripts/reserve-sizing.mjs\` from \`${samplePath.split("/").slice(-2).join("/")}\` (fetched ${sample.fetchedAt}), ${PATHS.toLocaleString("en-US")} paths per cell._`);
L.push("");
L.push("**The series.** Kraken ZEC/USD, the open candle dropped:");
L.push("");
L.push("| Interval | Candles | From | To | Last close | Realized vol per bar | Annualized |");
L.push("|---|---|---|---|---|---|---|");
for (const iv of INTERVALS) {
  const s = S[iv], v = realizedVol(s), c = s.candles;
  L.push(`| ${iv} min | ${c.length} | ${iso(c[0].t)} | ${iso(c[c.length - 1].t)} | $${c[c.length - 1].c.toLocaleString("en-US")} | ${pct(v.perBar)} | **${pct(v.annualized, 0)}** |`);
}
L.push("");
L.push(`**The ladder at entry HF ${ENTRY_HF}** (\`ladderFor\`, Kamino's 40 % cap against LT 65 %): ${geo.rungs.map((r) => `${r.label} ${r.hf} (re-arms ${r.disarmHf})`).join(" · ")}. The reserve is **${pctN(geo.reserveFraction * 100)} of the debt** — one rung-2 repay, ${rungBy("repay").hf} → ${rungBy("repay").disarmHf}.`);
L.push("");
L.push("| Price move needed | Warn | Repay | De-risk | Emergency | Liquidation (HF 1) |");
L.push("|---|---|---|---|---|---|");
L.push(`| from entry | ${["warn", "repay", "derisk", "emergency"].map((k) => `−${pctN(geo.fromEntryPct[k], 1)}`).join(" | ")} | −${pctN(geo.liquidationFromEntryPct, 1)} |`);
L.push(`| from rung 2's disarm level (the reserve just spent) | — | — | ${["derisk", "emergency"].map((k) => `−${pctN(geo.fromDisarm2Pct[k], 1)}`).join(" | ")} | −${pctN(geo.liquidationFromDisarm2Pct, 1)} |`);
L.push("");

/* empirical drops per horizon */
const GAP = geo.fromDisarm2Pct.derisk / 100; // the drop that takes a just-refilled position to rung 3
const HORIZONS = [
  [15, 1, "15 min"], [15, 4, "1 h (15-min bars)"], [60, 1, "1 h"], [60, 4, "4 h"], [60, 24, "24 h"],
  [240, 6, "24 h (4-h bars)"], [240, 18, "3 d"], [240, 42, "7 d"], [1440, 1, "1 d"], [1440, 3, "3 d (daily)"], [1440, 7, "7 d (daily)"], [1440, 14, "14 d"], [1440, 30, "30 d"],
];
L.push(`**How far ZEC has actually fallen inside a window** — close to the lowest low within the next N bars, every start bar in the series. The column that matters is the last: how often the window held a drop of at least **${pctN(GAP * 100, 1)}**, which takes a position from rung 2's disarm level straight to rung 3 (ZEC sold).`);
L.push("");
L.push("| Window | Bars | Windows | Worst | p99 | p95 | ≥ rung-2→3 gap |");
L.push("|---|---|---|---|---|---|---|");
const EMP = {};
for (const [iv, bars, label] of HORIZONS) {
  const w = worstDropWithin(S[iv].candles, bars);
  EMP[label] = { ...w, freq: frequencyOfDrop(w.drops, GAP) };
  const f = EMP[label].freq;
  L.push(`| ${label} | ${bars} × ${iv} min | ${w.n} | **−${pctN(w.worst * 100, 1)}** | −${pctN(w.p99 * 100, 1)} | −${pctN(w.p95 * 100, 1)} | ${f === 0 ? "never" : `${pct(f, 2)} of windows`} |`);
}
L.push("");

/* Monte Carlo */
const REGIMES = [
  { iv: 60, label: "hourly bars, last 30 days", blockLen: 6, perDay: 24, landings: [[1, "lands in 1 h"], [24, "lands in 24 h"], [Infinity, "never lands"]] },
  { iv: 240, label: "4-hour bars, last 120 days", blockLen: 6, perDay: 6, landings: [[1, "lands in 4 h"], [6, "lands in 24 h"], [Infinity, "never lands"]] },
  { iv: 1440, label: "daily bars, last 2 years", blockLen: 5, perDay: 1, landings: [[1, "lands in 1 d"], [Infinity, "never lands"]] },
];
L.push(`**Monte Carlo.** Each regime block-bootstraps its own series' close-to-close log returns **with the mean removed** (a month in which ZEC rallied would otherwise carry the rally as drift; \`scripts/lp-sim.py\` is zero-drift for the same reason), every path starting at entry HF ${ENTRY_HF} with the ladder run once per bar. Coarser bars make the keeper look slower than it is — it polls every 30 s, so on a daily bar it would have acted at rung 2 long before the bar's close — and close-to-close ignores the wick, so the daily regime overstates what falls through the ladder and every regime understates the intra-bar low; the two errors pull opposite ways and neither is small. The bridge cases: the top-up lands after one bar (Fast or Standard — no series here resolves the difference), after a day (an outage), never (the loop unbuilt, or Circle down).`);
L.push("");
const CELLS = [];
for (const rg of REGIMES) {
  const returns = demean(logReturns(S[rg.iv].candles));
  for (const [days, horizon] of [[7, "7 d"], [30, "30 d"]]) {
    const bars = days * rg.perDay;
    L.push(`| ${rg.label}, ${horizon} · reserve = k × R | k | rung 2 reached | ZEC sold (rung 3 or 4) | liquidated | bridge needed | repays / path | idle USDC, % of debt | carry, % of debt / yr |`);
    L.push("|---|---|---|---|---|---|---|---|---|");
    for (const [landingBars, bridge] of rg.landings) {
      for (const k of [1, 2, 3, 5]) {
        const o = simulateLadder({ returns, bars, paths: PATHS, seed: 20260919 + k, blockLen: rg.blockLen, scale: 1, entryHf: ENTRY_HF, lt: LT, reserveMultiple: k, landingBars });
        CELLS.push({ regime: rg.label, horizon, bridge, k, ...o });
        L.push(`| ${bridge} | ${k} | ${pct(o.reachedRepay, 1)} | **${pct(o.zecSold, 2)}** | ${pct(o.reachedLiquidation, 2)} | ${pct(o.bridgeNeeded, 1)} | ${o.avgRepays.toFixed(2)} | ${pctN(k * geo.reserveFraction * 100, 1)} | ${pctN(k * geo.reserveFraction * KAMINO_USDC_BORROW_APR, 2)} |`);
      }
    }
    L.push("");
  }
}
/* replay: the ladder over the history as it happened, every start bar — no resampling, no de-meaning */
L.push("**Replay — the ladder run over the history exactly as it happened**, one window per start bar, nothing resampled and the drift left in. A position opened at every bar of the series and held for the window; the share of those windows on which the ladder sold ZEC. Overlapping windows, so one crash counts in every window that contains it — a description of the record, not an estimate.");
L.push("");
L.push("| Series | Window | Windows | k = 1: rung 2 reached | k = 1: ZEC sold | k = 3: ZEC sold | k = 5: ZEC sold | liquidated (k = 1) |");
L.push("|---|---|---|---|---|---|---|---|");
const REPLAY = [];
for (const [iv, bars, label] of [[60, 168, "7 d"], [240, 180, "30 d"], [1440, 30, "30 d"], [1440, 90, "90 d"]]) {
  const returns = logReturns(S[iv].candles);
  const windows = returns.length - bars + 1;
  const row = [1, 3, 5].map((k) => simulateLadder({ returns, bars, paths: windows, seed: 0, blockLen: 1, scale: 1, entryHf: ENTRY_HF, lt: LT, reserveMultiple: k, landingBars: Infinity, mode: "replay", startIndex: 0 }));
  REPLAY.push({ iv, bars, label, windows, k1: row[0], k3: row[1], k5: row[2] });
  L.push(`| ${iv} min bars | ${label} | ${windows} | ${pct(row[0].reachedRepay, 1)} | **${pct(row[0].zecSold, 2)}** | ${pct(row[1].zecSold, 2)} | ${pct(row[2].zecSold, 2)} | ${pct(row[0].reachedLiquidation, 2)} |`);
}
L.push("");

/* sensitivity: the entry HF (the cushion) against the reserve multiple */
L.push("**Sensitivity — the entry HF against the reserve.** The same 30-day, hourly-regime, nothing-lands cell at other entries (LT 65 %, so the loan-to-value each entry means is 0.65 ÷ HF); above 2.00 the acting rungs are the 2.00 ladder's (D10).");
L.push("");
L.push("| Entry HF (LTV) | k = 1: ZEC sold | k = 3: ZEC sold | k = 5: ZEC sold | rung 2 reached | idle USDC at k = 1 |");
L.push("|---|---|---|---|---|---|");
const hourlyDemeaned = demean(logReturns(S[60].candles));
for (const e of [1.625, 1.8, 2.0, 2.2]) {
  const row = [1, 3, 5].map((k) => simulateLadder({ returns: hourlyDemeaned, bars: 720, paths: PATHS, seed: 20260919 + k, blockLen: 6, scale: 1, entryHf: e, lt: LT, reserveMultiple: k, landingBars: Infinity }));
  L.push(`| ${e} (${pctN((LT / e) * 100, 1)}) | **${pct(row[0].zecSold, 2)}** | ${pct(row[1].zecSold, 2)} | ${pct(row[2].zecSold, 2)} | ${pct(row[0].reachedRepay, 1)} | ${pctN(ladderGeometry(e).reserveFraction * 100, 2)} of debt |`);
}
L.push("");
L.push(`Carry is the idle USDC × Kamino's USDC borrow APR (${KAMINO_USDC_BORROW_APR} % at the recorded read): the reserve is borrowed money that earns nothing while it waits (§14.3).`);
if (argv.includes("--json")) console.log(JSON.stringify({ sample: samplePath, entryHf: ENTRY_HF, lt: LT, geometry: geo, empirical: EMP, cells: CELLS, replay: REPLAY }, null, 1));
else console.log(L.join("\n"));
