import { test } from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { FEES } from "@zyo/shared";
import { DEMO_GATE_RAW, DEMO_MARKET, DEMO_SNAPSHOT_BLOCK, demoForecast, demoGate } from "../lib/demo";
import { reasonPlain, reasonText, verdictsFor, type GateEntry } from "../lib/gate";
import { exactHalfWidthPct, fmtHalfWidth } from "../lib/math";
import { fmtPct, fmtSignedPct } from "../lib/format";
import { recommend } from "../lib/recommend";

/**
 * MODEL NUMBER DRIFT GUARD.
 *
 * Every number this UI puts in front of a user about the yield model comes
 * from the gate payload, and the gate payload must agree, digit for digit,
 * with the published model tables. This test parses those tables and compares
 * them with what the app would actually RENDER — through the same formatters
 * the components use, not through a re-implementation.
 *
 * The source checked is services/yield/samples/MODEL-NUMBERS.md — in the repo, always present,
 * regenerated by `scripts/refresh-demo-snapshot.mjs` (or `cd services/yield && npm run model`) and copied
 * to docs/MODEL-NUMBERS-<date>.md. (Until 2026-09-13 a second rendering, the 2026-09-06 fix round's
 * hand-off /tmp/fix2/MODEL-NUMBERS-v2.md, was checked when present; that artefact is gone and the in-repo
 * report is the one record — docs/CONTRACT-ABI.md and docs/AUDIT-2026-09-06.md carry what that round shipped.)
 */

const REPO_DOC = join(__dirname, "../../services/yield/samples/MODEL-NUMBERS.md");

type Cell = { pool: string; setting: string; width: number; delayH: number; gross: string; net: string; realized: string; drag: string; lpNet: string; mcLpNet: string };
type UserNetRow = { pool: string; setting: string; collateral: string; ltvBps: number; lpNet: string; borrow: string; supply: string; userNet: string };

const clean = (s: string) => s.replace(/\*\*/g, "").trim();

function rows(doc: string): string[][] {
  return doc
    .split("\n")
    .filter((l) => l.trim().startsWith("|"))
    .map((l) => l.trim().replace(/^\|/, "").replace(/\|$/, "").split("|").map(clean));
}

/** The "per pool × setting" table, in either doc's column layout. */
function parseCells(doc: string): Cell[] {
  const out: Cell[] = [];
  for (const r of rows(doc)) {
    if (r.length < 11) continue;
    if (!/^(aero-[a-z0-9-]+|cbeth-weth)$/.test(r[0])) continue;
    if (!/^(sheltered|steady|working)$/.test(r[1])) continue;
    const w = r[2].match(/^(\d+)\s*\(/);
    const d = r[3].match(/^(\d+)h$/);
    if (!w || !d) continue;
    out.push({ pool: r[0], setting: r[1], width: Number(w[1]), delayH: Number(d[1]), gross: r[4], net: r[5], realized: r[6], drag: r[7], lpNet: r[8], mcLpNet: r[9] });
  }
  return out;
}

function parseUserNet(doc: string): UserNetRow[] {
  const out: UserNetRow[] = [];
  for (const r of rows(doc)) {
    if (r.length !== 8) continue;
    if (!/^aero-[a-z0-9-]+$/.test(r[0]) || !/^(sheltered|steady|working)$/.test(r[1])) continue;
    if (!/^(cbBTC|WETH)$/.test(r[2])) continue;
    const ltv = r[3].match(/^([\d.]+)%/);
    if (!ltv) continue;
    out.push({ pool: r[0], setting: r[1], collateral: r[2], ltvBps: Math.round(Number(ltv[1]) * 100), lpNet: r[4], borrow: r[5], supply: r[6], userNet: r[7] });
  }
  return out;
}

const gate = demoGate();
const find = (pool: string, setting: string, collateral: string): GateEntry | undefined => gate.verdicts.find((v) => v.poolId === pool && v.setting === setting && v.collateral === collateral);

/** How the app writes a percentage that may be absent. */
const shownSigned = (x: number | null, dp = 2) => (x === null ? "—" : fmtSignedPct(x, dp).replace("+", ""));
const shownPct = (x: number | null, dp = 2) => (x === null ? "—" : fmtPct(x, dp));

function checkDoc(label: string, path: string, t: { skip: (m: string) => void }): boolean {
  if (!existsSync(path)) {
    t.skip(`${label} not present in this checkout`);
    return false;
  }
  const doc = readFileSync(path, "utf8");
  const cells = parseCells(doc);
  assert.ok(cells.length >= 27, `${label}: parsed ${cells.length} model cells`);

  for (const c of cells) {
    // Every cell is served for BOTH collaterals; both must carry the same LP slice.
    for (const collateral of ["cbBTC", "WETH"]) {
      const v = find(c.pool, c.setting, collateral);
      assert.ok(v, `${label}: ${c.pool}/${c.setting}/${collateral} missing from the served gate`);
      assert.equal(v!.rangeWidthBps, c.width, `${label}: ${c.pool}/${c.setting} width`);
      assert.equal(v!.rebalanceDelayHours, c.delayH, `${label}: ${c.pool}/${c.setting} rebalance delay`);
      assert.equal(shownPct(v!.emissionsGrossPct), c.gross, `${label}: ${c.pool}/${c.setting} gross emissions`);
      assert.equal(shownPct(v!.emissionsNetPct), c.net, `${label}: ${c.pool}/${c.setting} net emissions`);
      assert.equal(shownPct(v!.emissionsRealizedPct), c.realized, `${label}: ${c.pool}/${c.setting} realized`);
      assert.equal(shownSigned(v!.dragPct), c.drag, `${label}: ${c.pool}/${c.setting} IL drag`);
      assert.equal(shownSigned(v!.lpNetPct), c.lpNet, `${label}: ${c.pool}/${c.setting} lpNet (published)`);
      assert.equal(shownSigned(v!.mcLpNetPct), c.mcLpNet, `${label}: ${c.pool}/${c.setting} mcLpNet (decides)`);
      // A cell the gate never prices must not render a number anywhere.
      if (c.lpNet === "—") {
        assert.equal(v!.lpNetPct, null, `${label}: ${c.pool}/${c.setting} publishes an lpNet the gate never computed`);
        assert.equal(v!.mcLpNetPct, null);
        assert.deepEqual(v!.userNet, [], `${label}: ${c.pool}/${c.setting} publishes a user-net ladder for an unpriced cell`);
      }
      // The exact half-width the model priced at, and the string the UI shows.
      const half = exactHalfWidthPct(c.width);
      assert.equal(fmtHalfWidth(c.width), `±${half.toFixed(half < 10 ? 2 : 1)}%`);
      assert.ok(Math.abs(v!.halfWidth * 100 - half) < 1e-9, `${label}: ${c.pool}/${c.setting} halfWidth`);
    }
  }

  const un = parseUserNet(doc);
  const pricedCells = (doc.match(/^\| (?:aero-[a-z0-9-]+|cbeth-weth) \| (?:sheltered|steady|working) \|.*\| \*\*-?[\d.]+%\*\* \| \*\*-?[\d.]+%\*\* \|/gm) ?? []).length;
  assert.equal(un.length, pricedCells * 6, `${label}: parsed ${un.length} user-net rows for ${pricedCells} priced cells`);
  for (const r of un) {
    const v = find(r.pool, r.setting, r.collateral);
    assert.ok(v, `${label}: ${r.pool}/${r.setting}/${r.collateral} missing`);
    const cell = v!.userNet.find((u) => u.ltvBps === r.ltvBps);
    assert.ok(cell, `${label}: ${r.pool}/${r.setting}/${r.collateral}/${r.ltvBps} missing from userNet`);
    assert.equal(shownSigned(cell!.userNetPct), r.userNet, `${label}: ${r.pool}/${r.setting}/${r.collateral}/${r.ltvBps} userNet`);
    assert.equal(shownSigned(v!.lpNetPct), r.lpNet, `${label}: ${r.pool}/${r.setting} lpNet in the user-net table`);
    // The doc publishes the borrow as read (4.5174 % on 2026-09-12, four decimals); the app renders three.
    assert.equal(shownPct(v!.borrowAprPct, 3), shownPct(Number(r.borrow.replace("%", "")), 3), `${label}: borrow rate`);
    assert.equal(shownPct(v!.collateralSupplyAprPct, 3), shownPct(Number(r.supply.replace("%", "")), 3), `${label}: ${r.collateral} supply rate`);
  }
  return true;
}

test("every model number the UI renders matches services/yield/samples/MODEL-NUMBERS.md", (t) => {
  checkDoc("MODEL-NUMBERS.md", REPO_DOC, t);
});

test("the gate's own headline numbers are the ones the product quotes", () => {
  assert.equal(gate.borrowAprPct, DEMO_MARKET.usdcBorrowAprPct);
  // The gate and the market snapshot are ONE read since the ledger re-read of 2026-09-12: the same
  // block (51,226,072) and the same borrow digits. snapshot.test.ts keeps the freshness rule for the
  // day one of them moves without the other.
  assert.equal(gate.borrowAprPct, DEMO_MARKET.usdcBorrowAprPct);
  assert.match(DEMO_GATE_RAW.borrowSource, new RegExp(`at block ${DEMO_SNAPSHOT_BLOCK}\\b`));
  // Advanced mode prints the engine's cut and Oilskin's fee side by side.
  assert.equal(gate.engineFeeBps, 1500);
  assert.equal(gate.engineFeeBps! / 100, 15);
  assert.equal(FEES.performanceBps / 100, 10);
  // The gate's gauge words are the snapshot's instant: one pinned read since 2026-09-13 (the source stamps it with milliseconds).
  assert.equal(Date.parse(gate.emissionsSampledAt), Date.parse(DEMO_MARKET.readAt));
  assert.ok(gate.mcCalibrationGeneratedAt.length > 0, "the MC calibration stamp is served and shown");
  assert.equal(gate.stale, false);
  assert.equal(gate.verdicts.length, 81, "27 pool × setting cells × 3 collaterals");
});

test("nothing beats the borrow on both models; every row has both a code and a sentence; and the forecast still recommends the least bad cell rather than refusing (D4/D5)", () => {
  assert.equal(DEMO_GATE_RAW.qualifying.length, 0);
  assert.equal(gate.verdicts.filter((v) => v.qualifies).length, 0);
  for (const collateral of ["cbBTC", "WETH", "cbZEC"] as const) {
    const rows = verdictsFor(gate, collateral);
    assert.ok(rows.length > 0);
    for (const v of rows) {
      assert.equal(v.qualifies, false);
      assert.ok(v.reason, `${v.poolId}/${v.setting}/${collateral} has no reason`);
      assert.notEqual(reasonText(v.reason), "", "Advanced mode text");
      assert.ok(reasonPlain(v.reason).length > 30, "Simple mode sentence");
      assert.ok(!reasonText(v.reason).includes("_"), `reason code leaked into Advanced text: ${reasonText(v.reason)}`);
    }
    // Sorted best-lpNet first, so the "closest miss" Simple mode names is the real one.
    const nets = rows.map((v) => v.lpNetPct ?? -Infinity);
    assert.deepEqual(nets, [...nets].sort((a, b) => b - a));
  }
  const rec = recommend(demoForecast(), "cbBTC", 4000);
  assert.equal(rec.kind, "lp", "the forecast recommends the least bad priced cell — the user decides");
  if (rec.kind === "lp") {
    assert.equal(rec.cell.poolId, "aero-cbbtc-usdc");
    assert.equal(rec.cell.setting, "sheltered");
    assert.equal(rec.positive, false);
    assert.ok(rec.userNetPct < 0);
    assert.ok(rec.why.includes(`${DEMO_MARKET.usdcBorrowAprPct.toFixed(2)}%`), rec.why);
    assert.ok(/still a loss/.test(rec.why), rec.why);
    assert.ok(!rec.why.includes("_"), rec.why);
  }
});

test("the best priced cell is exactly the one MODEL-NUMBERS-2026-09-13 publishes (literal pins, the mutation guard)", () => {
  const best = find("aero-cbbtc-usdc", "sheltered", "cbBTC")!;
  assert.equal(best.lpNetPct, -3.75);
  assert.equal(best.mcLpNetPct, -3.68);
  assert.equal(best.dragPct, -15.25);
  assert.equal(best.emissionsGrossPct, 16.31);
  assert.equal(best.emissionsNetPct, 12.48);
  assert.equal(best.emissionsRealizedPct, 11.5);
  assert.equal(best.sigma, 0.4);
  assert.equal(best.breakEvenEmissionsMultiple, 1.72);
  assert.equal(best.userNet.find((u) => u.ltvBps === 3000)?.userNetPct, -2.47);
  assert.equal(best.userNet.find((u) => u.ltvBps === 4000)?.userNetPct, -3.3);
  assert.equal(best.userNet.find((u) => u.ltvBps === 6240)?.userNetPct, -5.15, "the top at the pinned 1.25 floor: 62.4 %");
  // Two more priced cells, at their 2026-09-13 values.
  assert.equal(find("aero-cbbtc-usdc", "steady", "cbBTC")!.lpNetPct, -10.01);
  assert.equal(find("aero-usdc-weth-5", "steady", "cbBTC")!.lpNetPct, -39.59);
  // WETH/cbBTC steady fell below the borrow before any drag on 2026-09-13 (net 3.12 % < 4.51 %; its
  // gauge's staked liquidity tripled overnight): refused before pricing, nothing published. (On
  // 2026-09-12 the cell in this state was WETH/USDC sheltered, priced again today at −16.95 %.)
  const wethSheltered = find("aero-weth-cbbtc", "steady", "cbBTC")!;
  assert.equal(wethSheltered.reason, "emissions_below_borrow");
  assert.equal(wethSheltered.lpNetPct, null);
  // …and the cell that must no longer publish anything at all (since 2026-09-05).
  const gone = find("aero-weth-cbbtc", "sheltered", "cbBTC")!;
  assert.equal(gone.reason, "emissions_below_borrow");
  assert.equal(gone.lpNetPct, null);
  assert.equal(gone.mcLpNetPct, null);
  assert.equal(gone.dragPct, null);
  assert.deepEqual(gone.userNet, []);
  // breakEvenSigma is no longer served on the no-σ cells.
  for (const setting of ["sheltered", "steady", "working"]) {
    const v = find("aero-weth-link", setting, "cbBTC")!;
    assert.equal(v.reason, "no_volatility_input");
    assert.equal(v.breakEvenSigma, null);
  }
});
